version: '3'

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped

  web:
    image: web:0.0.1
    container_name: web
    ports:
      - "${WEB_PORT}:80"
    restart: unless-stopped

  api:
    image: lana-api:0.0.1
    container_name: api
    restart: unless-stopped
    ports:
      - "${API_PORT}:3003"