version: '3'

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: web:0.0.1
    container_name: web
    ports:
      - "${WEB_PORT}:80"
    restart: unless-stopped

  api:
    image: lana-api:0.0.1
    depends_on:
      postgres:
        condition: service_healthy
    container_name: api
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    ports:
      - "${API_PORT}:3003"
